# Setup Postgres

version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    command: sh -c "yarn db:migrate && yarn backend:start-prod"
    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}

volumes:
  db:
    driver: local
