# Setup Postgres

version: '3.8'
services:
  test_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: saituri
      TZ: 'UTC'
    ports:
      - 5499:5432
    tmpfs:
      - /var/lib/postgresql/data
volumes:
  db:
    driver: local

